/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABtn: typeof import('anu-vue')['ABtn']
    ADataTable: typeof import('anu-vue')['ADataTable']
    AInput: typeof import('anu-vue')['AInput']
    AList: typeof import('anu-vue')['AList']
    ALoadingIcon: typeof import('anu-vue')['ALoadingIcon']
    AMenu: typeof import('anu-vue')['AMenu']
    ARadio: typeof import('anu-vue')['ARadio']
    ASelect: typeof import('anu-vue')['ASelect']
    ASwitch: typeof import('anu-vue')['ASwitch']
    ATabs: typeof import('anu-vue')['ATabs']
    Button: typeof import('./components/Button.vue')['default']
    FileForm: typeof import('./components/FileForm.vue')['default']
    FileInput: typeof import('./components/FileInput.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    LoginBtn: typeof import('./components/LoginBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
  }
}
