// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly VITE_LIGHTHOUSE_API_KEY: string;
  readonly VITE_HUDDLE_API_KEY: string;
  readonly VITE_HUDDLE_PROJECT_ID: string;
  readonly VITE_INFURA_API_KEY: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
