// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IDataCure$Type } from "./IDataCure";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDataCure"]: IDataCure$Type;
    ["contracts/IDataCure.sol:IDataCure"]: IDataCure$Type;
  }
}
