// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IDataCureAccess$Type } from "./IDataCureAccess";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDataCureAccess"]: IDataCureAccess$Type;
    ["contracts/IDataCureAccess.sol:IDataCureAccess"]: IDataCureAccess$Type;
  }
}
