// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IDataCureAccess$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IDataCureAccess",
  "sourceName": "contracts/IDataCureAccess.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "_userToken",
          "type": "uint256"
        },
        {
          "indexed": true,
          "internalType": "string",
          "name": "_cid",
          "type": "string"
        }
      ],
      "name": "GrandAccess",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "address",
          "name": "_dataCureAddr",
          "type": "address"
        }
      ],
      "name": "UpdateDataCureAddress",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "_userToken",
          "type": "uint256"
        },
        {
          "indexed": true,
          "internalType": "string",
          "name": "_cid",
          "type": "string"
        },
        {
          "indexed": false,
          "internalType": "bool",
          "name": "_listForSale",
          "type": "bool"
        }
      ],
      "name": "UploadData",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_userToken",
          "type": "uint256"
        },
        {
          "internalType": "string",
          "name": "_cid",
          "type": "string"
        }
      ],
      "name": "grandAccess",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_dataCureAddr",
          "type": "address"
        }
      ],
      "name": "updateDataCureFactory",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_userToken",
          "type": "uint256"
        },
        {
          "internalType": "string",
          "name": "_cid",
          "type": "string"
        },
        {
          "internalType": "bool",
          "name": "_listForSale",
          "type": "bool"
        }
      ],
      "name": "uploadData",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IDataCureAccess",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IDataCureAccess$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/IDataCureAccess.sol:IDataCureAccess",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IDataCureAccess$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IDataCureAccess",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IDataCureAccess$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/IDataCureAccess.sol:IDataCureAccess",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IDataCureAccess$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IDataCureAccess",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IDataCureAccess$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/IDataCureAccess.sol:IDataCureAccess",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IDataCureAccess$Type["abi"]>>;
}
