// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { DataCureAccess$Type } from "./DataCureAccess";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DataCureAccess"]: DataCureAccess$Type;
    ["contracts/DataCureAccess.sol:DataCureAccess"]: DataCureAccess$Type;
  }
}
