// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { DataCure$Type } from "./DataCure";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DataCure"]: DataCure$Type;
    ["contracts/DataCure.sol:DataCure"]: DataCure$Type;
  }
}
