// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Verifier$Type } from "./Verifier";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Verifier"]: Verifier$Type;
    ["contracts/Verifier.sol:Verifier"]: Verifier$Type;
  }
}
